add_executable(list6001 list6001.cpp list6001.hh)
add_executable(list6002 list6002.cpp list6002.hh)
add_executable(list6003 list6003.cpp)
add_executable(list6004 list6004.cpp)
add_executable(list6005 list6005.cpp)
add_executable(list6006 list6006.cpp)
add_executable(list6007 list6007.cpp)
add_executable(list6008 list6008.cpp)
add_executable(list6009 list6009.cpp list6009.hh)
add_executable(list6010 list6010.cpp list6010.hh)
add_executable(list6011 list6011.cpp list6011.hh)
add_executable(list6012 list6012.cpp list6012.hh)
add_executable(list6013 list6013.cpp list6013.hh)
add_executable(list6014 list6014.cpp list6014.hh)
add_executable(list6015 list6015.cpp list6015.hh)
add_executable(list6016 list6016.cpp list6016.hh)
add_executable(list6017 list6017.cpp list6017.hh)
add_executable(list6018 list6018.cpp)
add_executable(list6019 list6019.cpp)

