add_executable(list6701 list6701.cpp list6701.hh)
add_executable(list6702 list6702.cpp list6702.hh)
add_executable(list6703 list6703.cpp list6703.hh)
add_executable(list6704 list6704.cpp list6704.hh)
add_executable(list6705 list6705.cpp list6705.hh)
add_executable(list6706 list6706.cpp list6706.hh)
add_executable(list6707 list6707.cpp list6707.hh)
add_executable(list6708 list6708.cpp)
add_executable(list6709 list6709.cpp)
add_executable(list6710 list6710.cpp)
target_compile_options(list6710 PRIVATE $<$<CXX_COMPILER_ID:GNU>:-Wno-sign-compare>)
add_executable(list6711 list6711.cpp)
target_compile_options(list6711 PRIVATE $<$<CXX_COMPILER_ID:GNU>:-Wno-sign-compare>)
add_executable(list6712 list6712.cpp)
target_compile_options(list6712 PRIVATE $<$<CXX_COMPILER_ID:GNU>:-Wno-narrowing>)
add_executable(list6713 list6713.cpp)
add_executable(list6714 list6714.cpp list6714.hh)
add_executable(list6715 list6715.cpp)
add_executable(list6716 list6716.cpp)

