add_executable(list3101 list3101.cpp)
add_executable(list3102 list3102.cpp)
add_executable(list3103 list3103.cpp)
add_executable(list3104 list3104.cpp)
add_executable(list3105 list3105.cpp)
add_executable(list3106 list3106.cpp)
add_executable(list3107 list3107.cpp)
add_executable(list3108 list3108.cpp)
add_executable(list3109 list3109.cpp)
add_executable(list3110 list3110.cpp)
add_executable(list3111 list3111.cpp)
add_executable(list3112 list3112.cpp)

include_directories(..)
