add_executable(list3101 list3101.cpp)
add_executable(list3102 list3102.cpp list3102.hh)
add_executable(list3103 list3103.cpp list3103.hh)
add_executable(list3104 list3104.cpp list3104.hh)
add_executable(list3105 list3105.cpp)
add_executable(list3106 list3106.cpp list3106.hh)
add_executable(list3107 list3107.cpp list3107.hh)
add_executable(list3108 list3108.cpp)
add_executable(list3109 list3109.cpp list3109.hh)
add_executable(list3110 list3110.cpp list3110.hh)
add_executable(list3111 list3111.cpp list3111.hh)
add_executable(list3112 list3112.cpp)

include_directories(..)
