add_executable(list7001 list7001.cpp)
add_executable(list7002 list7002.cpp)
add_executable(list7003 list7003.cpp)
add_executable(list7004 list7004.cpp list7004.hh)
add_executable(list7005 list7005.cpp list7005.hh)
add_executable(list7006 list7006.cpp list7006.hh)
add_executable(list7007 list7007.cpp list7007.hh)
add_executable(list7008 list7008.cpp list7008.hh)

