add_executable(list5701 list5701.cpp list5701.hh)
add_executable(list5702 list5702.cpp)
add_executable(list5703 list5703.cpp list5703.hh)
add_executable(list5704 list5704.cpp)
add_executable(list5705 list5705.cpp list5705.hh)
add_executable(list5706 list5706.cpp)
add_executable(list5707 list5707.cpp)
add_executable(list5708 list5708.cpp)
add_executable(list5709 list5709.cpp)
add_executable(list5710 list5710.cpp)
add_executable(list5711 list5711.cpp)
add_executable(list5712 list5712.cpp)

include_directories(. ../chap53 ../chap45)
