add_executable(list3901 list3901.cpp list3901.hh)
add_executable(list3902 list3902.cpp)
add_executable(list3903 list3903.cpp list3903.hh)
add_executable(list3904 list3904.cpp list3904.hh)
add_executable(list3905 list3905.cpp)
add_executable(list3906 list3906.cpp list3906.hh)
add_executable(list3907 list3907.cpp list3907.hh)

